export const DataStory = [
    {
        "storyId": 1,
        "id": 1,
        "slug": "melawan-asumsi-yang-ada",
        "title": "asumsi untuk maju namun banyak rintangan",
        "content": "So, tidak ada salahnya kalau Anda masih ingin terus berusaha. Tapi hindari permainan asumsi ya. Kalau ada yang jadi ganjalan lebih baik ditanyakan. Tapi, jangan lupa untuk menerima semua kemungkinan jawabannya. Jangan sampai terlalu memaksakan dan malah jadi buang-buang waktu Anda. Demi terhindar dari rasa stuck dan sulit melupakan mantan, Anda harus terus melangkah maju!",
        "url": "https://via.placeholder.com/600/92c952",
      },
      {
        "storyId": 1,
        "id": 2,
        "slug": "pengertian-investasi",
        "title": "pengertian investasi untuk dia yang baru mencoba",
        "content": "Investasi adalah suatu kegiatan menanamkan modal, baik langsung maupun tidak, dengan harapan pada waktu nanti pemilik modal mendapatkan sejumlah keuntungan dari hasil penanaman modal tersebut.[1] Dalam Kamus Besar Bahasa Indonesia investasi berarti penanaman uang atau modal pada suatu perusahaan atau proyek untuk tujuan memperoleh keuntungan.[2] Secara umum investasi dapat diartikan sebagai meluangkan atau memanfaatkan waktu, uang atau tenaga demi keuntungan/manfaat pada masa datang. Jadi, investasi merupakan membeli sesuatu yang diharapkan pada masa yang akan datang dapat dijual kembali dengan nilai yang lebih tinggi dari semula.",
        "url": "https://via.placeholder.com/600/771796",
      },
      {
        "storyId": 1,
        "id": 3,
        "slug": "pengertian-investasi-untuk",
        "title": "pengertian investasi untuk dia yang baru mencoba",
        "content": "Investasi adalah suatu kegiatan menanamkan modal, baik langsung maupun tidak, dengan harapan pada waktu nanti pemilik modal mendapatkan sejumlah keuntungan dari hasil penanaman modal tersebut.[1] Dalam Kamus Besar Bahasa Indonesia investasi berarti penanaman uang atau modal pada suatu perusahaan atau proyek untuk tujuan memperoleh keuntungan.[2] Secara umum investasi dapat diartikan sebagai meluangkan atau memanfaatkan waktu, uang atau tenaga demi keuntungan/manfaat pada masa datang. Jadi, investasi merupakan membeli sesuatu yang diharapkan pada masa yang akan datang dapat dijual kembali dengan nilai yang lebih tinggi dari semula.",
        "url": "https://via.placeholder.com/600/24f355",
      },
      {
        "storyId": 1,
        "id": 4,
        "slug": "pengertian-investasi-coba",
        "title": "pengertian investasi untuk dia yang baru mencoba",
        "content": "Investasi adalah suatu kegiatan menanamkan modal, baik langsung maupun tidak, dengan harapan pada waktu nanti pemilik modal mendapatkan sejumlah keuntungan dari hasil penanaman modal tersebut.[1] Dalam Kamus Besar Bahasa Indonesia investasi berarti penanaman uang atau modal pada suatu perusahaan atau proyek untuk tujuan memperoleh keuntungan.[2] Secara umum investasi dapat diartikan sebagai meluangkan atau memanfaatkan waktu, uang atau tenaga demi keuntungan/manfaat pada masa datang. Jadi, investasi merupakan membeli sesuatu yang diharapkan pada masa yang akan datang dapat dijual kembali dengan nilai yang lebih tinggi dari semula.",
        "url": "https://via.placeholder.com/600/d32776",
      },
      {
        "storyId": 1,
        "id": 5,
        "slug": "pengertian-investasi-dia",
        "title": "pengertian investasi untuk dia yang baru mencoba",
        "content": "Investasi adalah suatu kegiatan menanamkan modal, baik langsung maupun tidak, dengan harapan pada waktu nanti pemilik modal mendapatkan sejumlah keuntungan dari hasil penanaman modal tersebut.[1] Dalam Kamus Besar Bahasa Indonesia investasi berarti penanaman uang atau modal pada suatu perusahaan atau proyek untuk tujuan memperoleh keuntungan.[2] Secara umum investasi dapat diartikan sebagai meluangkan atau memanfaatkan waktu, uang atau tenaga demi keuntungan/manfaat pada masa datang. Jadi, investasi merupakan membeli sesuatu yang diharapkan pada masa yang akan datang dapat dijual kembali dengan nilai yang lebih tinggi dari semula.",
        "url": "https://via.placeholder.com/600/f66b97",
      },
      {
        "storyId": 1,
        "id": 6,
        "slug": "asumsi-yang-ada",
        "title": "asumsi untuk maju namun banyak rintangan",
        "content": "So, tidak ada salahnya kalau Anda masih ingin terus berusaha. Tapi hindari permainan asumsi ya. Kalau ada yang jadi ganjalan lebih baik ditanyakan. Tapi, jangan lupa untuk menerima semua kemungkinan jawabannya. Jangan sampai terlalu memaksakan dan malah jadi buang-buang waktu Anda. Demi terhindar dari rasa stuck dan sulit melupakan mantan, Anda harus terus melangkah maju!",
        "url": "https://via.placeholder.com/600/56a8c2",
      },
      {
        "storyId": 1,
        "id": 7,
        "slug": "asumsi-yang-ada",
        "title": "asumsi untuk maju namun banyak rintangan",
        "content": "So, tidak ada salahnya kalau Anda masih ingin terus berusaha. Tapi hindari permainan asumsi ya. Kalau ada yang jadi ganjalan lebih baik ditanyakan. Tapi, jangan lupa untuk menerima semua kemungkinan jawabannya. Jangan sampai terlalu memaksakan dan malah jadi buang-buang waktu Anda. Demi terhindar dari rasa stuck dan sulit melupakan mantan, Anda harus terus melangkah maju!",
        "url": "https://via.placeholder.com/600/b0f7cc",
      },
]